[versions]
java = "17"
kotlin = "2.3.0"
android = "9.0.0"

[libraries]
autoservice = { module = "com.google.auto.service:auto-service", version = "1.1.1" }
autoservice-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version = "1.2.0" }
javapoet = { module = "com.squareup:javapoet", version = "1.13.0" }
junit = { module = "junit:junit", version = "4.13.2" }
junit5-bom = { module = "org.junit:junit-bom", version = "6.0.2" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit5-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "2.2.0" }
mockk = { module = "io.mockk:mockk", version = "1.14.7" }
uriKMP = { module = "com.eygraber:uri-kmp", version = "0.0.21" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
android-multiplatform = { id = "com.android.kotlin.multiplatform.library", version.ref = "android" }
dokka = { id = "org.jetbrains.dokka-javadoc", version = "2.1.0" }
gitVersion = { id = "io.github.gmazzo.gitversion", version = "1.5.1" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
jacoco-testkit = { id = "io.github.gmazzo.gradle.testkit.jacoco", version = "1.0.5" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version = "2.3.4" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
publicationsReport = { id = "io.github.gmazzo.publications.report", version = "1.3.3" }
