[versions]
java = "11"
kotlin = "1.9.22"

[libraries]
javapoet = { module = "com.squareup:javapoet", version = "1.13.0" }
junit = { module = "junit:junit", version = "4.13.2" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "1.15.3" }
mockk = { module = "io.mockk:mockk", version = "1.13.8" }

[plugins]
android = { id = "com.android.application", version = "8.2.1" }
buildConfig = "com.github.gmazzo.buildconfig:5.2.0"
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
jacoco-testkit = { id = "pl.droidsonroids.jacoco.testkit", version = "1.0.12" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
publicationsReport = { id = "io.github.gmazzo.publications.report", version = "1.2.4" }
