[versions]
kotlin = "1.9.0"

[libraries]
apache-commons-lang = { module = "org.apache.commons:commons-lang3", version = "3.13.0" }
javapoet = { module = "com.squareup:javapoet", version = "1.13.0" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "1.14.2" }
mockk = { module = "io.mockk:mockk", version = "1.13.5" }

[plugins]
android = { id = "com.android.application", version = "8.1.0" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "1.2.0" }
jacoco-testkit = { id = "pl.droidsonroids.jacoco.testkit", version = "1.0.12" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
