name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */24 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup host
        uses: ./.github/actions/setup-host
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
        with:
          repo-token: ${{ secrets.GRADLE_WRAPPER_UPDATER_TOKEN }}
          labels: dependencies
          merge-method: squash
